### ISSUE TITLE
Since 4.x the style doesn't do anything in portrait orientation. 

### ISSUE THREAD

**Issue by S0und** [m1kethai/StretchGPT-Userstyle#1]
Hi

With 3.x the style worked great on a monitor with vertical orientation. The chat conversation was hugging the edges of the screen.

But since 4.x, it doesn't do anything in this orientation. The same thing happens when I move the window to a horizontal screen. 

_Unless_ I open the Sidebar - which I don't normally use. 

Sidebar closed (vertical):

https://i.imgur.com/Ch1e54J.png

Sidebar closed (horizontal):

https://i.imgur.com/lATEBvO.png

Sidebar open (horizontal)

https://i.imgur.com/oNNZXaU.png

I'm not sure if this is the intended behavior.

**Comment by m1kethai** [comment]
Yeah, OpenAI pushed a pretty big layout update either last night or this morning and it broke everything in this userstyle except for the sidebar. 

I pushed a few hotfixes (to v4.04) as soon as I noticed today and everything seemed 100% again, but I just tested it again more carefully after seeing this and realized I actually missed something - everything looks fine when the sidebar's open, but all the key chat styles get totally bypassed if it's closed for some reason. 

Thanks for bringing this to my attention. I'm putting together a new fix right now, so you should be able to pull v4.05 within the next hour or so.

**Comment by m1kethai** [comment]
[4.0.5](https://userstyles.world/style/9821/stretchgpt-extra-wide-chatgpt-conversations) is good to go.

Looks like everything's working as intended again but if you catch anything else weird going on, just let me know!

**Comment by S0und** [comment]
Thank you for the quick fix!
